### ISSUE TITLE
[FEATURE] 룸메 매칭 - 나의 생활 습관 정보 설정

### ISSUE THREAD

**Issue by ummiih** [dormitoryFamilies/web-front#1]
## 🌴 작업 브랜치 

`feature/set-lifestyle-info`

## 💼 TASK 개요 

- 룸메 매칭 나의 생활 습관 정보를 설정하는 컴포넌트를 제작합니다.

## ✅ TODO 및 진행현황 

- [x] '나의 수면 패턴은 ?' - 취침시간, 기상시간, 잠버릇, 잠귀
- [x] '나의 흡연 음주는 ?' - 흡연 여부, 음주 빈도, 주사
- [x] '나의 생활 방식은 ?' - 샤워 시간대, 샤워시간, 청소
- [x] '나의 체질은 ?' - 더위, 추위
- [x] '나의 MBTI는?'
- [x] '나의 본가가는 빈도는?' - 본가가는 빈도
- [x] '음식은 어떤가요?' - 야식, 방안에서
- [x] '나는 주로 어떤 편인가요?' - 휴대폰소리, 향수
- [x] '시험기간에 나는 ?' - 공부장소, 시험 준비
- [x] '기타 생활방식은 ?' - 운동, 벌레
