### ISSUE TITLE
[FEATURE] 온보딩 페이지 기능 구현

### ISSUE THREAD

**Issue by ummiih** [dormitoryFamilies/web-front#12]
## 🌴 작업 브랜치 

`feature/onboarding-page`

## 💼 TASK 개요 

온보딩 페이지 기능을 구현합니다. 
<img width="1067" alt="image" src="https://github.com/user-attachments/assets/42e663d2-2669-4d60-813c-ee9e17ff7bbc">

## ✅ TODO 및 진행현황 

- [ ] 서비스 접근 권한 안내
- [ ] 프로필 설정 - 닉네임
- [ ] 학생정보입력 - 학과 학번
- [ ] 학생정보입력 - 학생증
