### ISSUE TITLE
[REFACTOR] 로그인 api 구조 변경에 따른 게시판 페이지 구현

### ISSUE THREAD

**Issue by ummiih** [dormitoryFamilies/web-front#16]
## 🌴 작업 브랜치 

`fix/refactor-board-api`

## 🔨 Refactor 개요 

- 로그인 부분의 구조 변경에 따라, api변경을 진행합니다.

## ✅ TODO 및 진행현황 

- [x] 게시글 글쓰기 구조 변경
- [x] 게시판 글 불러오는 구조 변경
- [x] 게시글 디테일 페이지 구조 변경
- [ ] 게시글 수정 구조 변경
