### ISSUE TITLE
[FEATURE] 룸메 매칭 프로필 상세보기 페이지

### ISSUE THREAD

**Issue by ummiih** [dormitoryFamilies/web-front#9]
## 🌴 작업 브랜치 

`feature/roommate-profile-details`

## 💼 TASK 개요 

룸메 매칭 상대방의 프로필을 상세하게 볼 수 있는 페이지 기능을 구현합니다.
<img width="937" alt="image" src="https://github.com/user-attachments/assets/177a48f0-26be-4c80-80a8-7985240b2f2f">

## ✅ TODO 및 진행현황 

- [x] 기본 프로필 퍼블리싱
- [x] 기본 프로필 api 연결
- [x] 룸메 매칭 정보 퍼블리싱
- [x] 룸메 매칭 정보 api 연결
